name: Live Proxy Updater

on:
  schedule:
    - cron: '0 * * * *'  # Menjadwalkan workflow untuk berjalan setiap 1 jam
  workflow_dispatch:

jobs:
  run-bun:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Clone repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'Access-At'
          repository: 'proxy-scraping'
          access-token: ${{ secrets.TOKEN }}


      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies and run
        run: |
        cd proxy-scraping
        bun install
        bun run index.ts

      - name: Copy files proxy
        run: |
          find proxy-scraping -type f \( -name "*.txt" -o -name "*.json" \) ! -name "package.json" ! -name "tsconfig.json" -exec cp {} . \;
          rm -rf proxy-scraping

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push changes
        run: |
          git add .
          git commit -m "Automated commit: Proxy updated"
          git push
